apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: cinder.csi.openstack.org
  labels:
{{ include "csi-cinder-driver.labels" . | indent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
