apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  labels:
{{ include "csi-cinder-driver.labels" . | indent 4 }}
data:
  cloud.conf: {{ .Values.cloudConfig | required "cloudConfig is required" | b64enc | quote }}
