apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
{{ include "csi-cinder-driver.labels" . | indent 4 }}
provisioner: cinder.csi.openstack.org
